#pragma once

#define GAME_MAJOR_VERSION 0
#define GAME_MINOR_VERSION 1
#define GAME_PATCH_VERSION 0
#define GAME_HOTFIX_VERSION 0

//Automatically modified DO NOT TOUCH MANUALLY
#define GAME_BUILD_NUMBER 1337

#define GAME_VERSION_STRING (GAME_MAJOR_VERSION + "." + GAME_MINOR_VERSION + "." + GAME_PATCH_VERSION + "." + GAME_BUILD_NUMBER + "." GAME_HOTFIX_VERSION)
#define GAME_VERSION_SHORT_STRING (GAME_MAJOR_VERSION + "." GAME_MINOR_VERSION)